Restaurants/Models/Cuisines.cs
using System.Collections.Generic;

namespace Restaurant.Models
{
  public class Cuisines
    {
        public Cuisines()
        {
            this.Restaurants = new HashSet<Restaurants>();
        }

        public int CuisinesId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Restaurants> Restaurants { get; set; }
    }
}

Restaurants/Models/RestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurant.Models
{
  public class RestaurantContext : DbContext
  {
    public virtual DbSet<Cuisines> Cuisines { get; set; }
    public DbSet<Restaurants> Restaurants { get; set; }

    public RestaurantContext(DbContextOptions options) : base(options) { }
  }
}

Restaurants/Models/Restaurants.cs
namespace Restaurant.Models
{
  public class Restaurants
  {
    public int RestaurantsId { get; set; }
    public string Description { get; set; }
    public string Address { get; set; }
    public string Review { get; set; }

    public int CuisinesId { get; set; }

    public virtual Cuisines Cuisines { get; set; }
  }


}

Restaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace Restaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly RestaurantContext _db;

    public CuisinesController(RestaurantContext db)
    {
      _db = db;
    }
            
    [HttpGet]    
    public ActionResult Index()
    {
      List<Cuisines> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisines cuisines)
    {
      _db.Cuisines.Add(cuisines);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Cuisines thisCuisines = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisinesId == id);
      return View(thisCuisines);
    }
     public ActionResult Delete(int id)
    {
      var thisCuisines = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisinesId == id);
      return View(thisCuisines);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisinesId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisinesId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisines cuisines)
    {
      _db.Entry(cuisines).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

Restaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Restaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Restaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly RestaurantContext _db;

    public RestaurantsController(RestaurantContext db)
    {
      _db = db;
    }

    //   [HttpPost]
    //   public ActionResult Index(string restaurantDescription)
    //     {
    //         List<Restaurants> model = _db.Restaurants.Include(restaurants => restaurants.Cuisines).ToList(); 
    //         if (!String.IsNullOrEmpty(restaurantDescription)) 
    //         { 
    //             model = model.Where(s => s.Description.Contains(restaurantDescription)).Select(s => s).ToList(); 
    //         }
    //          return View(model);
    //     }
        [HttpPost]
      public ActionResult Index(string searchType, string value)
        {
            // Console.WriteLine(cuisines);
            List<Restaurants> model = _db.Restaurants.Include(restaurants => restaurants.Cuisines).ToList();
            if(searchType == "cuisine")
            {
                int cuisines = Int32.Parse(value);
                model  = _db.Restaurants.Where(restaurants => restaurants.CuisinesId == cuisines).Select(cuisine => cuisine).ToList();
            }
            else{
                model = model.Where(s => s.Description.Contains(value)).Select(s => s).ToList();
            }
            return View(model);
            
        } 

        public ActionResult Index()
        {
            List<Restaurants> model = _db.Restaurants.Include(restaurants => restaurants.Cuisines).ToList(); 
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.CuisinesId = new SelectList(_db.Cuisines, "CuisinesId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Restaurants restaurants)
        {
            _db.Restaurants.Add(restaurants);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Restaurants thisRestaurants = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantsId == id);
            Console.WriteLine(thisRestaurants);
            return View(thisRestaurants);
        }
         public ActionResult Delete(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantsId == id);
            return View(thisRestaurant);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantsId == id);
            _db.Restaurants.Remove(thisRestaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
         public ActionResult Edit(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(items => items.RestaurantsId == id);
            ViewBag.CuisinesId = new SelectList(_db.Cuisines, "CuisinesId", "Name");
            return View(thisRestaurant);
        }

        [HttpPost]
        public ActionResult Edit(Restaurants restaurants)
        {
            _db.Entry(restaurants).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Review(string searchType, string value)
        {
            List<Restaurants> model = _db.Restaurants.Include(restaurants => restaurants.Cuisines).ToList();
          
            return View();
        }

        [HttpPost]
        public ActionResult Show(string review)
        {
            List<Restaurants> model = _db.Restaurants.Include(restaurants => restaurants.Cuisines).ToList();
           
            
            model = model.Where(s => s.Description.Contains(review)).Select(s => s).ToList();
    
            return View("Show", model);
        }



  }
}

Restaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Cuisines

<h4>Add a new task</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add new cuisine" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

Restaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Cuisines

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to categories", "Index")

Restaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Restaurant.Models;
@model Restaurant.Models.Cuisines;

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): 
@Html.DisplayFor(model => model.Name)</h3>

<ul>
@if (@Model.Restaurants.Count == 0)
{
  <p>no items found</p>
}

@foreach (Restaurants restaurants in @Model.Restaurants)
{
  <li>Description: @restaurants.Description</li>
}
</ul>

<p>@Html.ActionLink("Back to cuisines", "Index")</p>
<p>@Html.ActionLink("Edit Cuisines", "Edit", new { id = Model.CuisinesId })</p>
<p>@Html.ActionLink("Delete Cuisines", "Delete", new { id = Model.CuisinesId })</p>

Restaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Cuisines

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CuisinesId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to cuisines", "Index")</p>

Restaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurant.Models;
@model List<Restaurant.Models.Cuisines>;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No categories have been added yet!</h3>
} 

@foreach (Cuisines cuisines in Model)
{
  <li>@Html.ActionLink($"{cuisines.Name}", "Details", new { id = cuisines.CuisinesId })</li>
}

<p>@Html.ActionLink("Add new cuisines", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Restaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Restaurants List!</h1>

<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See all Restaurants", "Index", "Restaurants")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Restaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Restaurants

<div class="container">

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

     @Html.LabelFor(model => model.Address)
    @Html.TextBoxFor(model => model.Address)




    @Html.LabelFor(model => model.Cuisines)
    @Html.DropDownList("CuisinesId")

    <input type="submit" value="Add new restaurant" class="btn btn-default" />

    
}
<p>@Html.ActionLink("Show all items", "Index")</p>
</div>

Restaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Restaurants

<div class="container">
<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")
</div>

Restaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}


@model Restaurant.Models.Restaurants

<div class="container">
<h2>Restaurant Details</h2>

<h3>@Html.DisplayNameFor(model => model.Description): 
  @Html.DisplayFor(model => model.Description)<h3>
  <h3>@Html.DisplayNameFor(model => model.Address): 
    @Html.DisplayFor(model => model.Address)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.RestaurantsId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.RestaurantsId })</p>
</div>

Restaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Restaurants

<div class="container">
<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantsId)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.Address)
    @Html.EditorFor(model => model.Address)
    @Html.LabelFor(model => model.Cuisines)
    @Html.DropDownList("CuisinesId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Restaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurant.Models;
@model List<Restaurant.Models.Restaurants>;

<div class="container">
<h1>Restaurant</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

@foreach (Restaurants restaurants in Model)
{
  <li>@Html.ActionLink($"{restaurants.Description}", "Details", new { id = restaurants.RestaurantsId }) | @restaurants.Cuisines.Name</li>
  <p>Address: @restaurants.Address</p>
}


<form method="post">
    
    <label for="restaurantDescription">Search for Restaurants</label>
    <input id="restaurantDescription" name="value" type="text">
    <button name="searchType" value="restaurant" type='submit'>Search</button>
</form>



<p>@Html.ActionLink("Add new restaurants", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

<form method="post">
    <select name = "value">
    <option value= >Select a number</option>
    <option value ="3">mexican</option>
    <option value ="2">thai</option>
    <option value ="4">indian</option>
    </select>
    <button name="searchType" value="cuisine" type='submit'>Search</button>
</form>
</div>

<p>@Html.ActionLink("Add a Review", "Review" , "Restaurants")</p>

Restaurants/Views/Restaurants/Review.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Restaurants



<form method="post">
    
    <label for="review">Search a Restaurants to review:</label>
    <input id="review" name="review" type="text">
    <button name="searchType" value="review" type='submit'>Search</button>

</form>

Restaurants/Views/Restaurants/Show.cshtml
@{
  Layout = "_Layout";
}

@model Restaurant.Models.Restaurants

 <h3>@Html.DisplayNameFor(model => model.Review): 
  @Html.DisplayFor(model => model.Review)</h3>

Restaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>